version: '3'

volumes:
    postgres_data: {}

services:
    django:
        build:
            context: .
            dockerfile: docker/django/Dockerfile
        command: /start-dev.sh
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file: .env
