version: 2.1

executors:
  machine-executor:
    machine:
      image: circleci/classic:latest

commands:
  base-command:
    steps:
      - setup_remote_docker
      - checkout
      - run: make config.env

jobs:
  flake8:
    executor: machine-executor
    steps:
      - base-command
      - run: docker-compose run django ls -la
      - run: docker-compose run django flake8
      - run: make flake8

  test:
    executor: machine-executor
    steps:
      - base-command
      - run: pwd
      - run: ls -la
      - run: docker-compose run django ls -la
      - run: docker-compose run django python manage.py test
      - run: make test

workflows:
  version: 2.1
  flake_and_test:
    jobs:
      - flake8
      - test