version: 2.1

executors:
  machine-executor:
    machine:
      image: circleci/classic:latest

commands:
  base-command:
    steps:
      - checkout
      - run: make config.env

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  flake8:
    executor: machine-executor
    steps:
      - base-command
      - run: make flake8

  test:
    executor: machine-executor
    steps:
      - base-command
      - run: make test

  coverage:
    executor: machine-executor
    steps:
      - base-command
      - run: make coverage
      - codecov/upload:
          file: .coverage

workflows:
  version: 2.1
  flake_and_test:
    jobs:
      - flake8
      - test